### ISSUE TITLE
Cause: java.lang.StackOverflowError

### ISSUE THREAD

**Issue by urtheone** [simonschiller/prefiller#2]
` Cause: java.lang.StackOverflowError
	at org.gradle.api.internal.provider.DefaultProperty.calculateValueFrom(DefaultProperty.java:128)
	at org.gradle.api.internal.provider.DefaultProperty.calculateValueFrom(DefaultProperty.java:25)
	at org.gradle.api.internal.provider.AbstractProperty.doCalculateValue(AbstractProperty.java:133)
	at org.gradle.api.internal.provider.AbstractProperty.calculateOwnValue(AbstractProperty.java:127)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:103)
	at org.gradle.api.internal.provider.DefaultProperty.calculateValueFrom(DefaultProperty.java:128)
	at org.gradle.api.internal.provider.DefaultProperty.calculateValueFrom(DefaultProperty.java:25)
	at org.gradle.api.internal.provider.AbstractProperty.doCalculateValue(AbstractProperty.java:133)
	at org.gradle.api.internal.provider.AbstractProperty.calculateOwnValue(AbstractProperty.java:127)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:103)
`

i use this plugin and it need to update my project to gradle 6.5, this happened after i updete.

**Comment by simonschiller** [comment]
Hi, thanks for the report!

Are you sure this is caused by this plugin? Does it work if you remove the plugin? Does it work with previous versions of Gradle? I can't really find anything related to this plugin in the stacktrace and the sample included also uses Gradle 6.5.
